version: '3.1'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${NGINX_CONF}:/etc/nginx/nginx.conf
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:php8.1
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DEBUG: 0
    volumes:
      - ${UPLOADS_INI}:/usr/local/etc/php/conf.d/uploads.ini
      - wordpress:/var/www/html
      - ./wordpress-files/plugins/${MAILHOG_PLUGIN}:/var/www/html/wp-content/plugins/${MAILHOG_PLUGIN}
      - ./wordpress-files/plugins/product-import-export-for-woo:/var/www/html/wp-content/plugins/product-import-export-for-woo
      - ./wordpress-files/themes/letsmake:/var/www/html/wp-content/themes/letsmake
      - ./wordpress-files/themes/child-letsmake:/var/www/html/wp-content/themes/child-letsmake
  #      - ${WP_DIRECTORY}:/var/www/html # uncomment if you need local wp files

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db:/var/lib/mysql
#      - ${DB_LOCAL_DATA}:/var/lib/mysql # uncomment if you need local database data

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 50M
    ports:
      - ${PMA_ADDRESS}:80
    depends_on:
      - db
    links:
      - db:db

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  wordpress:
  db:
